version: '3'
services:
  web:
    image: my-python-app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./chrome_data:/app/chrome_data
      - ./download:/app/download
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
